-- 0001_init.sql — generated by db/generate-ddl.js. Regenerate, do not hand-edit.
-- Source: scripts/schema-snapshot.json (base appr7CZdBQ966kwvL, fetched 2026-06-12T17:36:53.645Z) + drift spec.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE OR REPLACE FUNCTION gen_rec_id() RETURNS text AS $$
  SELECT 'rec' || substr(replace(gen_random_uuid()::text, '-', ''), 1, 17)
$$ LANGUAGE sql VOLATILE;

CREATE OR REPLACE FUNCTION touch_updated_at() RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ── Roles ─────────────────────────────
CREATE TABLE IF NOT EXISTS "roles" (
  "rec_id" text PRIMARY KEY DEFAULT gen_rec_id(),
  "id" text,
  "name" text,
  "description" text,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "idx_roles_id" ON "roles" ("id");
CREATE INDEX IF NOT EXISTS "idx_roles_updated_at" ON "roles" ("updated_at");
DROP TRIGGER IF EXISTS "trg_roles_touch" ON "roles";
CREATE TRIGGER "trg_roles_touch" BEFORE UPDATE ON "roles" FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

-- ── Permissions ─────────────────────────────
CREATE TABLE IF NOT EXISTS "permissions" (
  "rec_id" text PRIMARY KEY DEFAULT gen_rec_id(),
  "id" text,
  "key" text,
  "label" text,
  "category" text,
  "created_at" timestamptz DEFAULT now(),
  "description" text,
  "sort_order" bigint,
  "updated_at" timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "idx_permissions_id" ON "permissions" ("id");
CREATE INDEX IF NOT EXISTS "idx_permissions_updated_at" ON "permissions" ("updated_at");
DROP TRIGGER IF EXISTS "trg_permissions_touch" ON "permissions";
CREATE TRIGGER "trg_permissions_touch" BEFORE UPDATE ON "permissions" FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

-- ── RolePermissions ─────────────────────────────
CREATE TABLE IF NOT EXISTS "role_permissions" (
  "rec_id" text PRIMARY KEY DEFAULT gen_rec_id(),
  "id" text,
  "role_id" text,
  "permission_id" text,
  "allowed" text,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "idx_role_permissions_id" ON "role_permissions" ("id");
CREATE INDEX IF NOT EXISTS "idx_role_permissions_role_id" ON "role_permissions" ("role_id");
CREATE INDEX IF NOT EXISTS "idx_role_permissions_permission_id" ON "role_permissions" ("permission_id");
CREATE INDEX IF NOT EXISTS "idx_role_permissions_updated_at" ON "role_permissions" ("updated_at");
DROP TRIGGER IF EXISTS "trg_role_permissions_touch" ON "role_permissions";
CREATE TRIGGER "trg_role_permissions_touch" BEFORE UPDATE ON "role_permissions" FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

-- ── UserPermissionOverrides ─────────────────────────────
CREATE TABLE IF NOT EXISTS "user_permission_overrides" (
  "rec_id" text PRIMARY KEY DEFAULT gen_rec_id(),
  "id" text,
  "user_id" text,
  "permission_id" text,
  "allowed" text,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "idx_user_permission_overrides_id" ON "user_permission_overrides" ("id");
CREATE INDEX IF NOT EXISTS "idx_user_permission_overrides_user_id" ON "user_permission_overrides" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_user_permission_overrides_permission_id" ON "user_permission_overrides" ("permission_id");
CREATE INDEX IF NOT EXISTS "idx_user_permission_overrides_updated_at" ON "user_permission_overrides" ("updated_at");
DROP TRIGGER IF EXISTS "trg_user_permission_overrides_touch" ON "user_permission_overrides";
CREATE TRIGGER "trg_user_permission_overrides_touch" BEFORE UPDATE ON "user_permission_overrides" FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

-- ── Users ─────────────────────────────
CREATE TABLE IF NOT EXISTS "users" (
  "rec_id" text PRIMARY KEY DEFAULT gen_rec_id(),
  "id" text,
  "clerk_user_id" text,
  "email" text,
  "first_name" text,
  "last_name" text,
  "role_id" text,
  "status" text,
  "scope" text,
  "last_login_at" timestamptz,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now(),
  "clerk_image_url" text,
  "department_id" text,
  "eligibility_verifications" text,
  "conflicts" text,
  "is_support_staff" boolean,
  "resolved_tickets" text
);
CREATE INDEX IF NOT EXISTS "idx_users_id" ON "users" ("id");
CREATE INDEX IF NOT EXISTS "idx_users_clerk_user_id" ON "users" ("clerk_user_id");
CREATE INDEX IF NOT EXISTS "idx_users_role_id" ON "users" ("role_id");
CREATE INDEX IF NOT EXISTS "idx_users_updated_at" ON "users" ("updated_at");
CREATE INDEX IF NOT EXISTS "idx_users_department_id" ON "users" ("department_id");
DROP TRIGGER IF EXISTS "trg_users_touch" ON "users";
CREATE TRIGGER "trg_users_touch" BEFORE UPDATE ON "users" FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

-- ── Marketers ─────────────────────────────
CREATE TABLE IF NOT EXISTS "marketers" (
  "rec_id" text PRIMARY KEY DEFAULT gen_rec_id(),
  "id" text,
  "user_id" text,
  "first_name" text,
  "last_name" text,
  "email" text,
  "phone" text,
  "region" text[],
  "division" text,
  "status" text,
  "created_at" timestamptz DEFAULT now(),
  "supervising_marketer" boolean,
  "updated_at" timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "idx_marketers_id" ON "marketers" ("id");
CREATE INDEX IF NOT EXISTS "idx_marketers_user_id" ON "marketers" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_marketers_updated_at" ON "marketers" ("updated_at");
DROP TRIGGER IF EXISTS "trg_marketers_touch" ON "marketers";
CREATE TRIGGER "trg_marketers_touch" BEFORE UPDATE ON "marketers" FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

-- ── ReferralSources ─────────────────────────────
CREATE TABLE IF NOT EXISTS "referral_sources" (
  "rec_id" text PRIMARY KEY DEFAULT gen_rec_id(),
  "id" text,
  "name" text,
  "type" text,
  "is_active" text,
  "created_at" timestamptz DEFAULT now(),
  "marketer_id" text,
  "source_entity" text,
  "updated_at" timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "idx_referral_sources_id" ON "referral_sources" ("id");
CREATE INDEX IF NOT EXISTS "idx_referral_sources_marketer_id" ON "referral_sources" ("marketer_id");
CREATE INDEX IF NOT EXISTS "idx_referral_sources_updated_at" ON "referral_sources" ("updated_at");
DROP TRIGGER IF EXISTS "trg_referral_sources_touch" ON "referral_sources";
CREATE TRIGGER "trg_referral_sources_touch" BEFORE UPDATE ON "referral_sources" FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

-- ── MarketerFacilities ─────────────────────────────
CREATE TABLE IF NOT EXISTS "marketer_facilities" (
  "rec_id" text PRIMARY KEY DEFAULT gen_rec_id(),
  "id" text,
  "marketer_id" text,
  "facility_id" text,
  "is_primary" boolean,
  "assigned_date" timestamptz,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "idx_marketer_facilities_id" ON "marketer_facilities" ("id");
CREATE INDEX IF NOT EXISTS "idx_marketer_facilities_marketer_id" ON "marketer_facilities" ("marketer_id");
CREATE INDEX IF NOT EXISTS "idx_marketer_facilities_facility_id" ON "marketer_facilities" ("facility_id");
CREATE INDEX IF NOT EXISTS "idx_marketer_facilities_updated_at" ON "marketer_facilities" ("updated_at");
DROP TRIGGER IF EXISTS "trg_marketer_facilities_touch" ON "marketer_facilities";
CREATE TRIGGER "trg_marketer_facilities_touch" BEFORE UPDATE ON "marketer_facilities" FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

-- ── Campaigns ─────────────────────────────
CREATE TABLE IF NOT EXISTS "campaigns" (
  "rec_id" text PRIMARY KEY DEFAULT gen_rec_id(),
  "id" text,
  "name" text,
  "division" text,
  "region" text,
  "start_date" timestamptz,
  "end_date" timestamptz,
  "status" text,
  "notes" text,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "idx_campaigns_id" ON "campaigns" ("id");
CREATE INDEX IF NOT EXISTS "idx_campaigns_updated_at" ON "campaigns" ("updated_at");
DROP TRIGGER IF EXISTS "trg_campaigns_touch" ON "campaigns";
CREATE TRIGGER "trg_campaigns_touch" BEFORE UPDATE ON "campaigns" FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

-- ── CampaignMarketers ─────────────────────────────
CREATE TABLE IF NOT EXISTS "campaign_marketers" (
  "rec_id" text PRIMARY KEY DEFAULT gen_rec_id(),
  "id" text,
  "campaign_id" text,
  "marketer_id" text,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "idx_campaign_marketers_id" ON "campaign_marketers" ("id");
CREATE INDEX IF NOT EXISTS "idx_campaign_marketers_campaign_id" ON "campaign_marketers" ("campaign_id");
CREATE INDEX IF NOT EXISTS "idx_campaign_marketers_marketer_id" ON "campaign_marketers" ("marketer_id");
CREATE INDEX IF NOT EXISTS "idx_campaign_marketers_updated_at" ON "campaign_marketers" ("updated_at");
DROP TRIGGER IF EXISTS "trg_campaign_marketers_touch" ON "campaign_marketers";
CREATE TRIGGER "trg_campaign_marketers_touch" BEFORE UPDATE ON "campaign_marketers" FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

-- ── Physicians ─────────────────────────────
CREATE TABLE IF NOT EXISTS "physicians" (
  "rec_id" text PRIMARY KEY DEFAULT gen_rec_id(),
  "id" text,
  "first_name" text,
  "last_name" text,
  "npi" text,
  "phone" text,
  "fax" text,
  "address_street" text,
  "address_city" text,
  "address_state" text,
  "address_zip" text,
  "is_pecos_enrolled" boolean,
  "is_opra_enrolled" boolean,
  "pecos_last_checked" timestamptz,
  "facility_id" text,
  "is_active" text,
  "created_at" timestamptz DEFAULT now(),
  "npi_status" text,
  "npi_checked_at" timestamptz,
  "npi_provider_name" text,
  "npi_details" jsonb,
  "opra_last_checked" timestamptz,
  "order_refer_flags" jsonb,
  "verification_last_run_at" timestamptz,
  "verification_checked_by_id" text,
  "updated_at" timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "idx_physicians_id" ON "physicians" ("id");
CREATE INDEX IF NOT EXISTS "idx_physicians_facility_id" ON "physicians" ("facility_id");
CREATE INDEX IF NOT EXISTS "idx_physicians_verification_checked_by_id" ON "physicians" ("verification_checked_by_id");
CREATE INDEX IF NOT EXISTS "idx_physicians_updated_at" ON "physicians" ("updated_at");
DROP TRIGGER IF EXISTS "trg_physicians_touch" ON "physicians";
CREATE TRIGGER "trg_physicians_touch" BEFORE UPDATE ON "physicians" FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

-- ── Patients ─────────────────────────────
CREATE TABLE IF NOT EXISTS "patients" (
  "rec_id" text PRIMARY KEY DEFAULT gen_rec_id(),
  "id" text,
  "first_name" text,
  "last_name" text,
  "dob" timestamptz,
  "gender" text,
  "address_street" text,
  "address_city" text,
  "address_state" text,
  "address_zip" text,
  "phone_primary" text,
  "phone_secondary" text,
  "email" text,
  "medicaid_number" text,
  "medicare_number" text,
  "insurance_plan" text,
  "insurance_id" text,
  "division" text,
  "emergency_contact_name" text,
  "emergency_contact_phone" text,
  "emergency_contact_email" text,
  "is_active" text,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now(),
  "county" text,
  "insurance_plans" jsonb,
  "insurance_plan_details" jsonb,
  "eligibility_verifications" text,
  "conflicts" text
);
CREATE INDEX IF NOT EXISTS "idx_patients_id" ON "patients" ("id");
CREATE INDEX IF NOT EXISTS "idx_patients_insurance_id" ON "patients" ("insurance_id");
CREATE INDEX IF NOT EXISTS "idx_patients_updated_at" ON "patients" ("updated_at");
DROP TRIGGER IF EXISTS "trg_patients_touch" ON "patients";
CREATE TRIGGER "trg_patients_touch" BEFORE UPDATE ON "patients" FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

-- ── Referrals ─────────────────────────────
CREATE TABLE IF NOT EXISTS "referrals" (
  "rec_id" text PRIMARY KEY DEFAULT gen_rec_id(),
  "id" text,
  "patient_id" text,
  "referral_source_id" text,
  "facility_id" text,
  "marketer_id" text,
  "campaign_id" text,
  "intake_owner_id" text,
  "division" text,
  "current_stage" text,
  "services_requested" text[],
  "priority" text,
  "referral_date" timestamptz,
  "f2f_date" timestamptz,
  "f2f_expiration" timestamptz,
  "f2f_urgency" text,
  "physician_id" text,
  "is_pecos_verified" text,
  "is_opra_verified" boolean,
  "ntuc_reason" text,
  "ntuc_financial_impact" text,
  "hold_reason" text,
  "hold_owner_id" text,
  "hold_expected_resolution" timestamptz,
  "hold_return_stage" text,
  "admitted_date" timestamptz,
  "soc_scheduled_date" timestamptz,
  "soc_completed_date" timestamptz,
  "hchb_entered" boolean,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now(),
  "entity_id" text,
  "sn_age_group" text,
  "discard_reason" text,
  "discard_explanation" text,
  "ntuc_request_origin_stage" text,
  "ntuc_requested_by" text,
  "ntuc_requested_at" text,
  "code_95" text,
  "clinical_review_decision" text,
  "clinical_review_by" text,
  "clinical_review_at" text,
  "active_opwdd_case_id" text,
  "opwdd_route_started_at" timestamptz,
  "opwdd_route_started_by_id" text,
  "opwdd_conversion_ready" boolean,
  "opwdd_handoff_status" text,
  "in_clinical_review" boolean,
  "clinical_review_pushed_at" timestamptz,
  "clinical_review_completed_at" timestamptz,
  "clinical_review_completed_by_id" text,
  "eligibility_completed_at" timestamptz,
  "eligibility_completed_by_id" text,
  "eligibility_returned_to_intake_at" timestamptz,
  "eligibility_returned_to_intake_note" text,
  "eligibility_returned_to_intake_by_id" text,
  "requires_urgent_care" boolean,
  "urgent_care_marked_at" timestamptz,
  "urgent_care_marked_by_id" text,
  "urgent_care_note" text,
  "eligibility_recheck_requested_at" text,
  "eligibility_recheck_return_stage" text,
  "emr_onboarded_at" text,
  "emr_onboarded_by_id" text,
  "recent_hospitalization" boolean,
  "hospitalization_date" text,
  "soc_scheduled_at" text,
  "staffing_confirmed_at" text,
  "staffing_confirmed_by_id" text,
  "soc_scheduled_by_id" text
);
CREATE INDEX IF NOT EXISTS "idx_referrals_id" ON "referrals" ("id");
CREATE INDEX IF NOT EXISTS "idx_referrals_patient_id" ON "referrals" ("patient_id");
CREATE INDEX IF NOT EXISTS "idx_referrals_referral_source_id" ON "referrals" ("referral_source_id");
CREATE INDEX IF NOT EXISTS "idx_referrals_facility_id" ON "referrals" ("facility_id");
CREATE INDEX IF NOT EXISTS "idx_referrals_marketer_id" ON "referrals" ("marketer_id");
CREATE INDEX IF NOT EXISTS "idx_referrals_campaign_id" ON "referrals" ("campaign_id");
CREATE INDEX IF NOT EXISTS "idx_referrals_intake_owner_id" ON "referrals" ("intake_owner_id");
CREATE INDEX IF NOT EXISTS "idx_referrals_physician_id" ON "referrals" ("physician_id");
CREATE INDEX IF NOT EXISTS "idx_referrals_hold_owner_id" ON "referrals" ("hold_owner_id");
CREATE INDEX IF NOT EXISTS "idx_referrals_updated_at" ON "referrals" ("updated_at");
CREATE INDEX IF NOT EXISTS "idx_referrals_entity_id" ON "referrals" ("entity_id");
CREATE INDEX IF NOT EXISTS "idx_referrals_active_opwdd_case_id" ON "referrals" ("active_opwdd_case_id");
CREATE INDEX IF NOT EXISTS "idx_referrals_opwdd_route_started_by_id" ON "referrals" ("opwdd_route_started_by_id");
CREATE INDEX IF NOT EXISTS "idx_referrals_clinical_review_completed_by_id" ON "referrals" ("clinical_review_completed_by_id");
CREATE INDEX IF NOT EXISTS "idx_referrals_eligibility_completed_by_id" ON "referrals" ("eligibility_completed_by_id");
CREATE INDEX IF NOT EXISTS "idx_referrals_eligibility_returned_to_intake_by_id" ON "referrals" ("eligibility_returned_to_intake_by_id");
CREATE INDEX IF NOT EXISTS "idx_referrals_urgent_care_marked_by_id" ON "referrals" ("urgent_care_marked_by_id");
CREATE INDEX IF NOT EXISTS "idx_referrals_emr_onboarded_by_id" ON "referrals" ("emr_onboarded_by_id");
CREATE INDEX IF NOT EXISTS "idx_referrals_staffing_confirmed_by_id" ON "referrals" ("staffing_confirmed_by_id");
CREATE INDEX IF NOT EXISTS "idx_referrals_soc_scheduled_by_id" ON "referrals" ("soc_scheduled_by_id");
DROP TRIGGER IF EXISTS "trg_referrals_touch" ON "referrals";
CREATE TRIGGER "trg_referrals_touch" BEFORE UPDATE ON "referrals" FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

-- ── StageHistory ─────────────────────────────
CREATE TABLE IF NOT EXISTS "stage_history" (
  "rec_id" text PRIMARY KEY DEFAULT gen_rec_id(),
  "id" text,
  "referral_id" text,
  "from_stage" text,
  "to_stage" text,
  "changed_by_id" text,
  "reason" text,
  "metadata" jsonb,
  "timestamp" timestamptz,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "idx_stage_history_id" ON "stage_history" ("id");
CREATE INDEX IF NOT EXISTS "idx_stage_history_referral_id" ON "stage_history" ("referral_id");
CREATE INDEX IF NOT EXISTS "idx_stage_history_changed_by_id" ON "stage_history" ("changed_by_id");
CREATE INDEX IF NOT EXISTS "idx_stage_history_updated_at" ON "stage_history" ("updated_at");
DROP TRIGGER IF EXISTS "trg_stage_history_touch" ON "stage_history";
CREATE TRIGGER "trg_stage_history_touch" BEFORE UPDATE ON "stage_history" FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

-- ── Notes ─────────────────────────────
CREATE TABLE IF NOT EXISTS "notes" (
  "rec_id" text PRIMARY KEY DEFAULT gen_rec_id(),
  "id" text,
  "patient_id" text,
  "referral_id" text,
  "author_id" text,
  "content" text,
  "is_pinned" boolean,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "idx_notes_id" ON "notes" ("id");
CREATE INDEX IF NOT EXISTS "idx_notes_patient_id" ON "notes" ("patient_id");
CREATE INDEX IF NOT EXISTS "idx_notes_referral_id" ON "notes" ("referral_id");
CREATE INDEX IF NOT EXISTS "idx_notes_author_id" ON "notes" ("author_id");
CREATE INDEX IF NOT EXISTS "idx_notes_updated_at" ON "notes" ("updated_at");
DROP TRIGGER IF EXISTS "trg_notes_touch" ON "notes";
CREATE TRIGGER "trg_notes_touch" BEFORE UPDATE ON "notes" FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

-- ── Files ─────────────────────────────
CREATE TABLE IF NOT EXISTS "files" (
  "rec_id" text PRIMARY KEY DEFAULT gen_rec_id(),
  "id" text,
  "patient_id" text,
  "referral_id" text,
  "uploaded_by_id" text,
  "file_name" text,
  "file_type" text,
  "file_size" bigint,
  "r2_key" text,
  "r2_url" text,
  "category" text,
  "created_at" timestamptz DEFAULT now(),
  "f2f_visit_date" text,
  "opwdd_case_id" text,
  "document_subtype" text,
  "document_date" timestamptz,
  "document_valid_through" timestamptz,
  "verified_current_by_id" text,
  "verified_current_at" timestamptz,
  "authorization_id" text,
  "updated_at" timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "idx_files_id" ON "files" ("id");
CREATE INDEX IF NOT EXISTS "idx_files_patient_id" ON "files" ("patient_id");
CREATE INDEX IF NOT EXISTS "idx_files_referral_id" ON "files" ("referral_id");
CREATE INDEX IF NOT EXISTS "idx_files_uploaded_by_id" ON "files" ("uploaded_by_id");
CREATE INDEX IF NOT EXISTS "idx_files_opwdd_case_id" ON "files" ("opwdd_case_id");
CREATE INDEX IF NOT EXISTS "idx_files_verified_current_by_id" ON "files" ("verified_current_by_id");
CREATE INDEX IF NOT EXISTS "idx_files_authorization_id" ON "files" ("authorization_id");
CREATE INDEX IF NOT EXISTS "idx_files_updated_at" ON "files" ("updated_at");
DROP TRIGGER IF EXISTS "trg_files_touch" ON "files";
CREATE TRIGGER "trg_files_touch" BEFORE UPDATE ON "files" FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

-- ── InsuranceChecks ─────────────────────────────
CREATE TABLE IF NOT EXISTS "insurance_checks" (
  "rec_id" text PRIMARY KEY DEFAULT gen_rec_id(),
  "id" text,
  "referral_id" text,
  "patient_id" text,
  "checked_by_id" text,
  "check_source" text,
  "check_date" timestamptz,
  "medicare_part_a" text,
  "medicare_part_b" text,
  "medicaid_active" boolean,
  "managed_care_plan" text,
  "managed_care_id" text,
  "has_open_hh_episode" boolean,
  "open_episode_agency" text,
  "hospice_overlap" boolean,
  "snf_present" boolean,
  "hospital_present" boolean,
  "qmb_status" boolean,
  "cdpap_active" boolean,
  "auth_required" boolean,
  "disenrollment_needed" boolean,
  "result_summary" text,
  "raw_response" text,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "idx_insurance_checks_id" ON "insurance_checks" ("id");
CREATE INDEX IF NOT EXISTS "idx_insurance_checks_referral_id" ON "insurance_checks" ("referral_id");
CREATE INDEX IF NOT EXISTS "idx_insurance_checks_patient_id" ON "insurance_checks" ("patient_id");
CREATE INDEX IF NOT EXISTS "idx_insurance_checks_checked_by_id" ON "insurance_checks" ("checked_by_id");
CREATE INDEX IF NOT EXISTS "idx_insurance_checks_managed_care_id" ON "insurance_checks" ("managed_care_id");
CREATE INDEX IF NOT EXISTS "idx_insurance_checks_updated_at" ON "insurance_checks" ("updated_at");
DROP TRIGGER IF EXISTS "trg_insurance_checks_touch" ON "insurance_checks";
CREATE TRIGGER "trg_insurance_checks_touch" BEFORE UPDATE ON "insurance_checks" FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

-- ── Conflicts ─────────────────────────────
CREATE TABLE IF NOT EXISTS "conflicts" (
  "rec_id" text PRIMARY KEY DEFAULT gen_rec_id(),
  "id" text,
  "referral_id" text,
  "type" text,
  "description" text,
  "severity" text,
  "status" text,
  "flagged_by_id" text,
  "resolved_by_id" text,
  "resolution_note" text,
  "resolved_at" timestamptz,
  "created_at" timestamptz DEFAULT now(),
  "source_module" text,
  "conflict_reasons" text,
  "details" text,
  "resolution_status" text,
  "updated_at" timestamptz DEFAULT now(),
  "patient_id" text,
  "created_by_id" text,
  "source_stage" text
);
CREATE INDEX IF NOT EXISTS "idx_conflicts_id" ON "conflicts" ("id");
CREATE INDEX IF NOT EXISTS "idx_conflicts_referral_id" ON "conflicts" ("referral_id");
CREATE INDEX IF NOT EXISTS "idx_conflicts_flagged_by_id" ON "conflicts" ("flagged_by_id");
CREATE INDEX IF NOT EXISTS "idx_conflicts_resolved_by_id" ON "conflicts" ("resolved_by_id");
CREATE INDEX IF NOT EXISTS "idx_conflicts_updated_at" ON "conflicts" ("updated_at");
CREATE INDEX IF NOT EXISTS "idx_conflicts_patient_id" ON "conflicts" ("patient_id");
CREATE INDEX IF NOT EXISTS "idx_conflicts_created_by_id" ON "conflicts" ("created_by_id");
DROP TRIGGER IF EXISTS "trg_conflicts_touch" ON "conflicts";
CREATE TRIGGER "trg_conflicts_touch" BEFORE UPDATE ON "conflicts" FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

-- ── Authorizations ─────────────────────────────
CREATE TABLE IF NOT EXISTS "authorizations" (
  "rec_id" text PRIMARY KEY DEFAULT gen_rec_id(),
  "id" text,
  "referral_id" text,
  "insurance_check_id" text,
  "plan_name" text,
  "auth_number" text,
  "services_authorized" text[],
  "status" text,
  "submitted_date" timestamptz,
  "approved_date" timestamptz,
  "effective_start" timestamptz,
  "effective_end" timestamptz,
  "denial_reason" text,
  "denial_document_file_id" text,
  "notes" text,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now(),
  "auth_status" text,
  "auth_start_date" date,
  "auth_end_date" date,
  "auth_visit_limit" bigint,
  "auth_unit_type" text,
  "follow_up_date" date,
  "sca_requested" boolean,
  "sca_status" text,
  "documented_exception" text,
  "patient_id" text,
  "payer_insurance_id" text,
  "follow_up_owner_user_id" text,
  "decided_by_user_id" text,
  "service_lines" jsonb,
  "coverage_status" text,
  "payer_type" text,
  "payer_order" text,
  "sources_checked" jsonb,
  "request_initial_date" timestamptz,
  "request_requested_from" text,
  "request_docs_sent" boolean,
  "follow_ups" jsonb
);
CREATE INDEX IF NOT EXISTS "idx_authorizations_id" ON "authorizations" ("id");
CREATE INDEX IF NOT EXISTS "idx_authorizations_referral_id" ON "authorizations" ("referral_id");
CREATE INDEX IF NOT EXISTS "idx_authorizations_insurance_check_id" ON "authorizations" ("insurance_check_id");
CREATE INDEX IF NOT EXISTS "idx_authorizations_denial_document_file_id" ON "authorizations" ("denial_document_file_id");
CREATE INDEX IF NOT EXISTS "idx_authorizations_updated_at" ON "authorizations" ("updated_at");
CREATE INDEX IF NOT EXISTS "idx_authorizations_patient_id" ON "authorizations" ("patient_id");
CREATE INDEX IF NOT EXISTS "idx_authorizations_payer_insurance_id" ON "authorizations" ("payer_insurance_id");
CREATE INDEX IF NOT EXISTS "idx_authorizations_follow_up_owner_user_id" ON "authorizations" ("follow_up_owner_user_id");
CREATE INDEX IF NOT EXISTS "idx_authorizations_decided_by_user_id" ON "authorizations" ("decided_by_user_id");
DROP TRIGGER IF EXISTS "trg_authorizations_touch" ON "authorizations";
CREATE TRIGGER "trg_authorizations_touch" BEFORE UPDATE ON "authorizations" FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

-- ── Tasks ─────────────────────────────
CREATE TABLE IF NOT EXISTS "tasks" (
  "rec_id" text PRIMARY KEY DEFAULT gen_rec_id(),
  "id" text,
  "referral_id" text,
  "patient_id" text,
  "title" text,
  "description" text,
  "type" text,
  "route_to_role" text,
  "assigned_to_id" text,
  "status" text,
  "priority" text,
  "due_date" timestamptz,
  "completed_at" timestamptz,
  "completed_by_id" text,
  "blocks_stage_progression" boolean,
  "source" text,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now(),
  "scheduled_date" timestamptz,
  "opwdd_case_id" text,
  "physician_id" text
);
CREATE INDEX IF NOT EXISTS "idx_tasks_id" ON "tasks" ("id");
CREATE INDEX IF NOT EXISTS "idx_tasks_referral_id" ON "tasks" ("referral_id");
CREATE INDEX IF NOT EXISTS "idx_tasks_patient_id" ON "tasks" ("patient_id");
CREATE INDEX IF NOT EXISTS "idx_tasks_assigned_to_id" ON "tasks" ("assigned_to_id");
CREATE INDEX IF NOT EXISTS "idx_tasks_completed_by_id" ON "tasks" ("completed_by_id");
CREATE INDEX IF NOT EXISTS "idx_tasks_updated_at" ON "tasks" ("updated_at");
CREATE INDEX IF NOT EXISTS "idx_tasks_opwdd_case_id" ON "tasks" ("opwdd_case_id");
CREATE INDEX IF NOT EXISTS "idx_tasks_physician_id" ON "tasks" ("physician_id");
DROP TRIGGER IF EXISTS "trg_tasks_touch" ON "tasks";
CREATE TRIGGER "trg_tasks_touch" BEFORE UPDATE ON "tasks" FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

-- ── Episodes ─────────────────────────────
CREATE TABLE IF NOT EXISTS "episodes" (
  "rec_id" text PRIMARY KEY DEFAULT gen_rec_id(),
  "id" text,
  "patient_id" text,
  "referral_id" text,
  "soc_date" timestamptz,
  "episode_start" timestamptz,
  "episode_end" text,
  "current_30day_period" bigint,
  "recert_due_date" timestamptz,
  "auth_window_start" text,
  "auth_window_end" text,
  "status" text,
  "revenue_risk_flag" boolean,
  "revenue_risk_reason" text,
  "hchb_synced" text,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "idx_episodes_id" ON "episodes" ("id");
CREATE INDEX IF NOT EXISTS "idx_episodes_patient_id" ON "episodes" ("patient_id");
CREATE INDEX IF NOT EXISTS "idx_episodes_referral_id" ON "episodes" ("referral_id");
CREATE INDEX IF NOT EXISTS "idx_episodes_updated_at" ON "episodes" ("updated_at");
DROP TRIGGER IF EXISTS "trg_episodes_touch" ON "episodes";
CREATE TRIGGER "trg_episodes_touch" BEFORE UPDATE ON "episodes" FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

-- ── TriageAdult ─────────────────────────────
CREATE TABLE IF NOT EXISTS "triage_adult" (
  "rec_id" text PRIMARY KEY DEFAULT gen_rec_id(),
  "id" text,
  "referral_id" text,
  "filled_by_id" text,
  "caregiver_name" text,
  "caregiver_phone" text,
  "caregiver_email" text,
  "has_pets" text,
  "pet_details" text,
  "has_homecare_services" text,
  "homecare_agency_name" text,
  "homecare_hours" text,
  "homecare_days" text,
  "has_community_hab" text,
  "services_needed" text[],
  "therapy_availability" text,
  "is_diabetic" text,
  "diabetes_monitor_by" text,
  "pcp_name" text,
  "pcp_last_visit" timestamptz,
  "pcp_phone" text,
  "pcp_fax" text,
  "pcp_address" text,
  "cm_name" text,
  "cm_company" text,
  "cm_phone" text,
  "cm_fax_or_email" text,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now(),
  "opwdd_status" text,
  "insurance_plan_name" text,
  "medicaid_number" text,
  "patient_name" text,
  "dob" timestamptz,
  "address" text,
  "email" text,
  "add_secondary_caregiver" text,
  "secondary_caregiver_name" text,
  "secondary_caregiver_phone" text,
  "has_smoking" text,
  "homecare_hours_days" text,
  "has_in_home_therapies" text,
  "current_therapy_services" text,
  "hha_hours_frequency" text,
  "health_conditions" text,
  "pcp_npi_number" text,
  "cco_name" text,
  "cm_fax" text,
  "cm_email" text,
  "pcp_physician_id" text
);
CREATE INDEX IF NOT EXISTS "idx_triage_adult_id" ON "triage_adult" ("id");
CREATE INDEX IF NOT EXISTS "idx_triage_adult_referral_id" ON "triage_adult" ("referral_id");
CREATE INDEX IF NOT EXISTS "idx_triage_adult_filled_by_id" ON "triage_adult" ("filled_by_id");
CREATE INDEX IF NOT EXISTS "idx_triage_adult_updated_at" ON "triage_adult" ("updated_at");
CREATE INDEX IF NOT EXISTS "idx_triage_adult_pcp_physician_id" ON "triage_adult" ("pcp_physician_id");
DROP TRIGGER IF EXISTS "trg_triage_adult_touch" ON "triage_adult";
CREATE TRIGGER "trg_triage_adult_touch" BEFORE UPDATE ON "triage_adult" FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

-- ── TriagePediatric ─────────────────────────────
CREATE TABLE IF NOT EXISTS "triage_pediatric" (
  "rec_id" text PRIMARY KEY DEFAULT gen_rec_id(),
  "id" text,
  "referral_id" text,
  "filled_by_id" text,
  "phone_call_made_to" text,
  "household_description" text,
  "has_pets" text,
  "pet_details" text,
  "has_homecare_services" text,
  "homecare_agency_name" text,
  "homecare_hours" text,
  "homecare_days" text,
  "boe_services" text,
  "has_community_hab" text,
  "services_needed" text[],
  "therapy_availability" text,
  "hha_hours_frequency" text,
  "is_diabetic" text,
  "diabetes_monitor_by" text,
  "immunizations_up_to_date" text,
  "school_bus_time" text,
  "hospitalization_note" text,
  "pcp_name" text,
  "pcp_last_visit" timestamptz,
  "pcp_phone" text,
  "pcp_fax" text,
  "pcp_address" text,
  "cm_name" text,
  "cm_company" text,
  "cm_phone" text,
  "potential_soc_date" timestamptz,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now(),
  "has_recent_hospitalization" text,
  "has_boe_services" text,
  "opwdd_status" text,
  "medicaid_number" text,
  "primary_caregiver_name" text,
  "primary_caregiver_phone" text,
  "add_secondary_caregiver" text,
  "secondary_caregiver_name" text,
  "secondary_caregiver_phone" text,
  "emergency_same_as_primary" text,
  "emergency_contact_name" text,
  "emergency_contact_phone" text,
  "email" text,
  "patient_name" text,
  "dob" timestamptz,
  "address" text,
  "has_smoking" text,
  "homecare_hours_days" text,
  "health_conditions" text,
  "cco_name" text,
  "cm_fax" text,
  "cm_email" text,
  "pcp_physician_id" text
);
CREATE INDEX IF NOT EXISTS "idx_triage_pediatric_id" ON "triage_pediatric" ("id");
CREATE INDEX IF NOT EXISTS "idx_triage_pediatric_referral_id" ON "triage_pediatric" ("referral_id");
CREATE INDEX IF NOT EXISTS "idx_triage_pediatric_filled_by_id" ON "triage_pediatric" ("filled_by_id");
CREATE INDEX IF NOT EXISTS "idx_triage_pediatric_updated_at" ON "triage_pediatric" ("updated_at");
CREATE INDEX IF NOT EXISTS "idx_triage_pediatric_pcp_physician_id" ON "triage_pediatric" ("pcp_physician_id");
DROP TRIGGER IF EXISTS "trg_triage_pediatric_touch" ON "triage_pediatric";
CREATE TRIGGER "trg_triage_pediatric_touch" BEFORE UPDATE ON "triage_pediatric" FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

-- ── ActivityLog ─────────────────────────────
CREATE TABLE IF NOT EXISTS "activity_log" (
  "rec_id" text PRIMARY KEY DEFAULT gen_rec_id(),
  "id" text,
  "actor_id" text,
  "patient_id" text,
  "referral_id" text,
  "action" text,
  "detail" text,
  "metadata" jsonb,
  "timestamp" timestamptz,
  "opwdd_case_id" text,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "idx_activity_log_id" ON "activity_log" ("id");
CREATE INDEX IF NOT EXISTS "idx_activity_log_actor_id" ON "activity_log" ("actor_id");
CREATE INDEX IF NOT EXISTS "idx_activity_log_patient_id" ON "activity_log" ("patient_id");
CREATE INDEX IF NOT EXISTS "idx_activity_log_referral_id" ON "activity_log" ("referral_id");
CREATE INDEX IF NOT EXISTS "idx_activity_log_opwdd_case_id" ON "activity_log" ("opwdd_case_id");
CREATE INDEX IF NOT EXISTS "idx_activity_log_updated_at" ON "activity_log" ("updated_at");
DROP TRIGGER IF EXISTS "trg_activity_log_touch" ON "activity_log";
CREATE TRIGGER "trg_activity_log_touch" BEFORE UPDATE ON "activity_log" FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

-- ── UserPreferences ─────────────────────────────
CREATE TABLE IF NOT EXISTS "user_preferences" (
  "rec_id" text PRIMARY KEY DEFAULT gen_rec_id(),
  "clerk_user_id" text,
  "subnav_enabled" boolean,
  "pinned_pages" jsonb,
  "split_screen_enabled" boolean,
  "dashboard_mode" text,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "idx_user_preferences_clerk_user_id" ON "user_preferences" ("clerk_user_id");
CREATE INDEX IF NOT EXISTS "idx_user_preferences_updated_at" ON "user_preferences" ("updated_at");
DROP TRIGGER IF EXISTS "trg_user_preferences_touch" ON "user_preferences";
CREATE TRIGGER "trg_user_preferences_touch" BEFORE UPDATE ON "user_preferences" FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

-- ── PermissionPresets ─────────────────────────────
CREATE TABLE IF NOT EXISTS "permission_presets" (
  "rec_id" text PRIMARY KEY DEFAULT gen_rec_id(),
  "id" text,
  "name" text,
  "description" text,
  "permissions" jsonb,
  "is_system" boolean,
  "created_at" text DEFAULT now(),
  "updated_at" text DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "idx_permission_presets_id" ON "permission_presets" ("id");
CREATE INDEX IF NOT EXISTS "idx_permission_presets_updated_at" ON "permission_presets" ("updated_at");
DROP TRIGGER IF EXISTS "trg_permission_presets_touch" ON "permission_presets";
CREATE TRIGGER "trg_permission_presets_touch" BEFORE UPDATE ON "permission_presets" FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

-- ── UserPermissions ─────────────────────────────
CREATE TABLE IF NOT EXISTS "user_permissions" (
  "rec_id" text PRIMARY KEY DEFAULT gen_rec_id(),
  "id" text,
  "user_id" text,
  "permissions" jsonb,
  "last_preset_id" text,
  "updated_at" text DEFAULT now(),
  "updated_by" text,
  "allowed_assignees" jsonb,
  "created_at" timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "idx_user_permissions_id" ON "user_permissions" ("id");
CREATE INDEX IF NOT EXISTS "idx_user_permissions_user_id" ON "user_permissions" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_user_permissions_last_preset_id" ON "user_permissions" ("last_preset_id");
CREATE INDEX IF NOT EXISTS "idx_user_permissions_updated_at" ON "user_permissions" ("updated_at");
DROP TRIGGER IF EXISTS "trg_user_permissions_touch" ON "user_permissions";
CREATE TRIGGER "trg_user_permissions_touch" BEFORE UPDATE ON "user_permissions" FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

-- ── TriageALF ─────────────────────────────
CREATE TABLE IF NOT EXISTS "triage_alf" (
  "rec_id" text PRIMARY KEY DEFAULT gen_rec_id(),
  "name" text,
  "notes" text,
  "assignee" jsonb,
  "status" text,
  "attachments" jsonb,
  "attachment_summary" text,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "idx_triage_alf_updated_at" ON "triage_alf" ("updated_at");
DROP TRIGGER IF EXISTS "trg_triage_alf_touch" ON "triage_alf";
CREATE TRIGGER "trg_triage_alf_touch" BEFORE UPDATE ON "triage_alf" FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

-- ── Departments ─────────────────────────────
CREATE TABLE IF NOT EXISTS "departments" (
  "rec_id" text PRIMARY KEY DEFAULT gen_rec_id(),
  "id" text,
  "name" text,
  "supervisor" text,
  "division" text,
  "department_scope_id" text,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "idx_departments_id" ON "departments" ("id");
CREATE INDEX IF NOT EXISTS "idx_departments_department_scope_id" ON "departments" ("department_scope_id");
CREATE INDEX IF NOT EXISTS "idx_departments_updated_at" ON "departments" ("updated_at");
DROP TRIGGER IF EXISTS "trg_departments_touch" ON "departments";
CREATE TRIGGER "trg_departments_touch" BEFORE UPDATE ON "departments" FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

-- ── DepartmentScopes ─────────────────────────────
CREATE TABLE IF NOT EXISTS "department_scopes" (
  "rec_id" text PRIMARY KEY DEFAULT gen_rec_id(),
  "id" text,
  "name" text,
  "stage_access" text[],
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "idx_department_scopes_id" ON "department_scopes" ("id");
CREATE INDEX IF NOT EXISTS "idx_department_scopes_updated_at" ON "department_scopes" ("updated_at");
DROP TRIGGER IF EXISTS "trg_department_scopes_touch" ON "department_scopes";
CREATE TRIGGER "trg_department_scopes_touch" BEFORE UPDATE ON "department_scopes" FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

-- ── Calls ─────────────────────────────
CREATE TABLE IF NOT EXISTS "calls" (
  "rec_id" text PRIMARY KEY DEFAULT gen_rec_id(),
  "call_id" text,
  "caller_usr_id" text,
  "related_patient_id" text,
  "conflict_id" text,
  "date_of_call" timestamptz,
  "topic" text,
  "call_answered" text,
  "call_description" text,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "idx_calls_call_id" ON "calls" ("call_id");
CREATE INDEX IF NOT EXISTS "idx_calls_caller_usr_id" ON "calls" ("caller_usr_id");
CREATE INDEX IF NOT EXISTS "idx_calls_related_patient_id" ON "calls" ("related_patient_id");
CREATE INDEX IF NOT EXISTS "idx_calls_conflict_id" ON "calls" ("conflict_id");
CREATE INDEX IF NOT EXISTS "idx_calls_updated_at" ON "calls" ("updated_at");
DROP TRIGGER IF EXISTS "trg_calls_touch" ON "calls";
CREATE TRIGGER "trg_calls_touch" BEFORE UPDATE ON "calls" FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

-- ── Facilities ─────────────────────────────
CREATE TABLE IF NOT EXISTS "facilities" (
  "rec_id" text PRIMARY KEY DEFAULT gen_rec_id(),
  "id" text,
  "name" text,
  "type" text,
  "address_street" text,
  "address_city" text,
  "address_state" text,
  "address_zip" bigint,
  "phone" text,
  "fax" text,
  "primary_contact_name" text,
  "primary_contact_phone" text,
  "primary_contact_email" text,
  "region" text,
  "services_provided_internally" text,
  "notes" text,
  "is_active" text,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "idx_facilities_id" ON "facilities" ("id");
CREATE INDEX IF NOT EXISTS "idx_facilities_updated_at" ON "facilities" ("updated_at");
DROP TRIGGER IF EXISTS "trg_facilities_touch" ON "facilities";
CREATE TRIGGER "trg_facilities_touch" BEFORE UPDATE ON "facilities" FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

-- ── NetworkFacilities ─────────────────────────────
CREATE TABLE IF NOT EXISTS "network_facilities" (
  "rec_id" text PRIMARY KEY DEFAULT gen_rec_id(),
  "id" text,
  "name" text,
  "region" text,
  "marketer_id" text,
  "case_manager" text,
  "type" text,
  "address_street" text,
  "zipcode" text,
  "entity_id" text,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "idx_network_facilities_id" ON "network_facilities" ("id");
CREATE INDEX IF NOT EXISTS "idx_network_facilities_marketer_id" ON "network_facilities" ("marketer_id");
CREATE INDEX IF NOT EXISTS "idx_network_facilities_entity_id" ON "network_facilities" ("entity_id");
CREATE INDEX IF NOT EXISTS "idx_network_facilities_updated_at" ON "network_facilities" ("updated_at");
DROP TRIGGER IF EXISTS "trg_network_facilities_touch" ON "network_facilities";
CREATE TRIGGER "trg_network_facilities_touch" BEFORE UPDATE ON "network_facilities" FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

-- ── PatientInsurancePlans ─────────────────────────────
CREATE TABLE IF NOT EXISTS "patient_insurance_plans" (
  "rec_id" text PRIMARY KEY DEFAULT gen_rec_id(),
  "id" text,
  "patient_id" text,
  "plan_name" text,
  "plan_id" text,
  "plan_type" text,
  "is_primary" text,
  "effective_start" text,
  "effective_end" text,
  "eligibility_verifications" text,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "idx_patient_insurance_plans_id" ON "patient_insurance_plans" ("id");
CREATE INDEX IF NOT EXISTS "idx_patient_insurance_plans_patient_id" ON "patient_insurance_plans" ("patient_id");
CREATE INDEX IF NOT EXISTS "idx_patient_insurance_plans_plan_id" ON "patient_insurance_plans" ("plan_id");
CREATE INDEX IF NOT EXISTS "idx_patient_insurance_plans_updated_at" ON "patient_insurance_plans" ("updated_at");
DROP TRIGGER IF EXISTS "trg_patient_insurance_plans_touch" ON "patient_insurance_plans";
CREATE TRIGGER "trg_patient_insurance_plans_touch" BEFORE UPDATE ON "patient_insurance_plans" FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

-- ── PatientInsurances ─────────────────────────────
CREATE TABLE IF NOT EXISTS "patient_insurances" (
  "rec_id" text PRIMARY KEY DEFAULT gen_rec_id(),
  "id" text,
  "patient_id" text,
  "payer_display_name" text,
  "insurance_category" text,
  "plan_name" text,
  "commercial_plan_name" text,
  "third_party_descriptor" text,
  "member_id" text,
  "group_number" text,
  "subscriber_name" text,
  "subscriber_relationship" text,
  "effective_date" text,
  "termination_date" text,
  "order_rank" text,
  "entered_from" text,
  "is_active_raw" boolean,
  "created_at" text DEFAULT now(),
  "updated_at" text DEFAULT now(),
  "eligibility_verifications" text
);
CREATE INDEX IF NOT EXISTS "idx_patient_insurances_id" ON "patient_insurances" ("id");
CREATE INDEX IF NOT EXISTS "idx_patient_insurances_patient_id" ON "patient_insurances" ("patient_id");
CREATE INDEX IF NOT EXISTS "idx_patient_insurances_member_id" ON "patient_insurances" ("member_id");
CREATE INDEX IF NOT EXISTS "idx_patient_insurances_updated_at" ON "patient_insurances" ("updated_at");
DROP TRIGGER IF EXISTS "trg_patient_insurances_touch" ON "patient_insurances";
CREATE TRIGGER "trg_patient_insurances_touch" BEFORE UPDATE ON "patient_insurances" FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

-- ── EligibilityVerifications ─────────────────────────────
CREATE TABLE IF NOT EXISTS "eligibility_verifications" (
  "rec_id" text PRIMARY KEY DEFAULT gen_rec_id(),
  "id" text,
  "patient_id" text,
  "insurance_id" text,
  "verification_status" text,
  "staff_confirmed_payer_type" text,
  "staff_confirmed_order_rank" text,
  "suggested_payer_type" text,
  "suggested_billing_model" text,
  "staff_confirmed_billing_model" text,
  "verification_sources" text[],
  "verification_date_time" timestamptz,
  "verified_by_user_id" text,
  "note_category" text,
  "note_text" text,
  "potential_conflict_detected" boolean,
  "requires_human_review" boolean,
  "synced_from_demographics_snapshot" text,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now(),
  "patient_insurance_id" text
);
CREATE INDEX IF NOT EXISTS "idx_eligibility_verifications_id" ON "eligibility_verifications" ("id");
CREATE INDEX IF NOT EXISTS "idx_eligibility_verifications_patient_id" ON "eligibility_verifications" ("patient_id");
CREATE INDEX IF NOT EXISTS "idx_eligibility_verifications_insurance_id" ON "eligibility_verifications" ("insurance_id");
CREATE INDEX IF NOT EXISTS "idx_eligibility_verifications_verified_by_user_id" ON "eligibility_verifications" ("verified_by_user_id");
CREATE INDEX IF NOT EXISTS "idx_eligibility_verifications_updated_at" ON "eligibility_verifications" ("updated_at");
CREATE INDEX IF NOT EXISTS "idx_eligibility_verifications_patient_insurance_id" ON "eligibility_verifications" ("patient_insurance_id");
DROP TRIGGER IF EXISTS "trg_eligibility_verifications_touch" ON "eligibility_verifications";
CREATE TRIGGER "trg_eligibility_verifications_touch" BEFORE UPDATE ON "eligibility_verifications" FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

-- ── DisenrollmentAssistanceFlags ─────────────────────────────
CREATE TABLE IF NOT EXISTS "disenrollment_assistance_flags" (
  "rec_id" text PRIMARY KEY DEFAULT gen_rec_id(),
  "id" text,
  "patient_id" text,
  "referral_id" text,
  "flag_type" text,
  "note" text,
  "follow_up_date" date,
  "follow_up_owner_user_id" text,
  "status" text,
  "created_by_user_id" text,
  "resolved_by_user_id" text,
  "resolution_note" text,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "idx_disenrollment_assistance_flags_id" ON "disenrollment_assistance_flags" ("id");
CREATE INDEX IF NOT EXISTS "idx_disenrollment_assistance_flags_patient_id" ON "disenrollment_assistance_flags" ("patient_id");
CREATE INDEX IF NOT EXISTS "idx_disenrollment_assistance_flags_referral_id" ON "disenrollment_assistance_flags" ("referral_id");
CREATE INDEX IF NOT EXISTS "idx_disenrollment_assistance_flags_follow_up_owner_user_id" ON "disenrollment_assistance_flags" ("follow_up_owner_user_id");
CREATE INDEX IF NOT EXISTS "idx_disenrollment_assistance_flags_created_by_user_id" ON "disenrollment_assistance_flags" ("created_by_user_id");
CREATE INDEX IF NOT EXISTS "idx_disenrollment_assistance_flags_resolved_by_user_id" ON "disenrollment_assistance_flags" ("resolved_by_user_id");
CREATE INDEX IF NOT EXISTS "idx_disenrollment_assistance_flags_updated_at" ON "disenrollment_assistance_flags" ("updated_at");
DROP TRIGGER IF EXISTS "trg_disenrollment_assistance_flags_touch" ON "disenrollment_assistance_flags";
CREATE TRIGGER "trg_disenrollment_assistance_flags_touch" BEFORE UPDATE ON "disenrollment_assistance_flags" FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

-- ── CursoryReview ─────────────────────────────
CREATE TABLE IF NOT EXISTS "cursory_review" (
  "rec_id" text PRIMARY KEY DEFAULT gen_rec_id(),
  "id" text,
  "reviewed_by" text,
  "referral_id" text,
  "face_to_face_document_present" boolean,
  "physician_certification_present" boolean,
  "patient_name_matches_referral" boolean,
  "dates_valid_within_90_days" boolean,
  "physician_signature_present" boolean,
  "diagnosis_icd_codes_listed" boolean,
  "homebound_status_documented" boolean,
  "services_disciplines_specified" boolean,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "idx_cursory_review_id" ON "cursory_review" ("id");
CREATE INDEX IF NOT EXISTS "idx_cursory_review_referral_id" ON "cursory_review" ("referral_id");
CREATE INDEX IF NOT EXISTS "idx_cursory_review_updated_at" ON "cursory_review" ("updated_at");
DROP TRIGGER IF EXISTS "trg_cursory_review_touch" ON "cursory_review";
CREATE TRIGGER "trg_cursory_review_touch" BEFORE UPDATE ON "cursory_review" FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

-- ── OPWDDEligibilityCases ─────────────────────────────
CREATE TABLE IF NOT EXISTS "opwdd_eligibility_cases" (
  "rec_id" text PRIMARY KEY DEFAULT gen_rec_id(),
  "id" text,
  "patient_id" text,
  "referral_id" text,
  "status" text,
  "sub_status" text,
  "assigned_enrollment_specialist_id" text,
  "opened_at" timestamptz,
  "closed_at" timestamptz,
  "closed_reason" text,
  "pcg_contact_name" text,
  "pcg_contact_phone" text,
  "pcg_contact_email" text,
  "pcg_relationship_to_patient" text,
  "pcg_willing_to_apply" boolean,
  "pcg_interested_in_wellbound_services" boolean,
  "interested_services" text[],
  "aba_only_referral" boolean,
  "article16_clinic_name" text,
  "psychological_eval_required" boolean,
  "psychological_eval_status" text,
  "psychological_eval_scheduled_for" timestamptz,
  "psychological_eval_received_at" timestamptz,
  "psychological_eval_valid_through" timestamptz,
  "psychosocial_required" boolean,
  "psychosocial_status" text,
  "psychosocial_scheduled_for" timestamptz,
  "psychosocial_received_at" timestamptz,
  "psychosocial_valid_through" timestamptz,
  "cco_id" text,
  "cco_name_snapshot" text,
  "submission_sent_at" timestamptz,
  "submission_sent_by_id" text,
  "submission_method" text,
  "submission_confirmation_number" text,
  "eligibility_determination" text,
  "eligibility_determined_at" timestamptz,
  "notice_received_at" timestamptz,
  "notice_received_method" text,
  "code_95_monitoring_started_at" timestamptz,
  "expected_code_95_window_start" timestamptz,
  "expected_code_95_window_end" timestamptz,
  "code_95_received_at" timestamptz,
  "converted_to_intake_at" timestamptz,
  "converted_by_id" text,
  "intake_handoff_note" text,
  "latest_blocker" text,
  "latest_blocker_note" text,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "idx_opwdd_eligibility_cases_id" ON "opwdd_eligibility_cases" ("id");
CREATE INDEX IF NOT EXISTS "idx_opwdd_eligibility_cases_patient_id" ON "opwdd_eligibility_cases" ("patient_id");
CREATE INDEX IF NOT EXISTS "idx_opwdd_eligibility_cases_referral_id" ON "opwdd_eligibility_cases" ("referral_id");
CREATE INDEX IF NOT EXISTS "idx_opwdd_eligibility_cases_assigned_enrollment_specialist_id" ON "opwdd_eligibility_cases" ("assigned_enrollment_specialist_id");
CREATE INDEX IF NOT EXISTS "idx_opwdd_eligibility_cases_cco_id" ON "opwdd_eligibility_cases" ("cco_id");
CREATE INDEX IF NOT EXISTS "idx_opwdd_eligibility_cases_submission_sent_by_id" ON "opwdd_eligibility_cases" ("submission_sent_by_id");
CREATE INDEX IF NOT EXISTS "idx_opwdd_eligibility_cases_converted_by_id" ON "opwdd_eligibility_cases" ("converted_by_id");
CREATE INDEX IF NOT EXISTS "idx_opwdd_eligibility_cases_updated_at" ON "opwdd_eligibility_cases" ("updated_at");
DROP TRIGGER IF EXISTS "trg_opwdd_eligibility_cases_touch" ON "opwdd_eligibility_cases";
CREATE TRIGGER "trg_opwdd_eligibility_cases_touch" BEFORE UPDATE ON "opwdd_eligibility_cases" FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

-- ── OPWDDCaseChecklistItems ─────────────────────────────
CREATE TABLE IF NOT EXISTS "opwdd_case_checklist_items" (
  "rec_id" text PRIMARY KEY DEFAULT gen_rec_id(),
  "id" text,
  "opwdd_case_id" text,
  "patient_id" text,
  "referral_id" text,
  "requirement_key" text,
  "requirement_label" text,
  "is_required" boolean,
  "status" text,
  "requested_at" timestamptz,
  "requested_by_id" text,
  "received_at" timestamptz,
  "received_by_id" text,
  "reviewed_at" timestamptz,
  "reviewed_by_id" text,
  "expires_at" timestamptz,
  "is_current" boolean,
  "satisfying_file_id" text,
  "notes" text,
  "sort_order" bigint,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "idx_opwdd_case_checklist_items_id" ON "opwdd_case_checklist_items" ("id");
CREATE INDEX IF NOT EXISTS "idx_opwdd_case_checklist_items_opwdd_case_id" ON "opwdd_case_checklist_items" ("opwdd_case_id");
CREATE INDEX IF NOT EXISTS "idx_opwdd_case_checklist_items_patient_id" ON "opwdd_case_checklist_items" ("patient_id");
CREATE INDEX IF NOT EXISTS "idx_opwdd_case_checklist_items_referral_id" ON "opwdd_case_checklist_items" ("referral_id");
CREATE INDEX IF NOT EXISTS "idx_opwdd_case_checklist_items_requested_by_id" ON "opwdd_case_checklist_items" ("requested_by_id");
CREATE INDEX IF NOT EXISTS "idx_opwdd_case_checklist_items_received_by_id" ON "opwdd_case_checklist_items" ("received_by_id");
CREATE INDEX IF NOT EXISTS "idx_opwdd_case_checklist_items_reviewed_by_id" ON "opwdd_case_checklist_items" ("reviewed_by_id");
CREATE INDEX IF NOT EXISTS "idx_opwdd_case_checklist_items_satisfying_file_id" ON "opwdd_case_checklist_items" ("satisfying_file_id");
CREATE INDEX IF NOT EXISTS "idx_opwdd_case_checklist_items_updated_at" ON "opwdd_case_checklist_items" ("updated_at");
DROP TRIGGER IF EXISTS "trg_opwdd_case_checklist_items_touch" ON "opwdd_case_checklist_items";
CREATE TRIGGER "trg_opwdd_case_checklist_items_touch" BEFORE UPDATE ON "opwdd_case_checklist_items" FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

-- ── Entities ─────────────────────────────
CREATE TABLE IF NOT EXISTS "entities" (
  "rec_id" text PRIMARY KEY DEFAULT gen_rec_id(),
  "id" text,
  "entity_name" text,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "idx_entities_id" ON "entities" ("id");
CREATE INDEX IF NOT EXISTS "idx_entities_updated_at" ON "entities" ("updated_at");
DROP TRIGGER IF EXISTS "trg_entities_touch" ON "entities";
CREATE TRIGGER "trg_entities_touch" BEFORE UPDATE ON "entities" FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

-- ── ClinicalReview ─────────────────────────────
CREATE TABLE IF NOT EXISTS "clinical_review" (
  "rec_id" text PRIMARY KEY DEFAULT gen_rec_id(),
  "id" text,
  "referral_id" text,
  "reviewed_by" text,
  "decision" text,
  "auth_required" boolean,
  "dx_reviewed" boolean,
  "comorbidities" boolean,
  "hospitalization" boolean,
  "skilled_need" boolean,
  "homebound" boolean,
  "physician_cert" boolean,
  "medical_necessity" boolean,
  "med_list" boolean,
  "high_risk_meds" boolean,
  "allergies" boolean,
  "safety_risks" boolean,
  "loc_sn" boolean,
  "loc_pt" boolean,
  "loc_ot" boolean,
  "loc_st" boolean,
  "loc_hha" boolean,
  "risk_high" boolean,
  "risk_moderate" boolean,
  "risk_low" boolean,
  "soc_timeframe" boolean,
  "scheduling_needs" boolean,
  "clinician_match" boolean,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "idx_clinical_review_id" ON "clinical_review" ("id");
CREATE INDEX IF NOT EXISTS "idx_clinical_review_referral_id" ON "clinical_review" ("referral_id");
CREATE INDEX IF NOT EXISTS "idx_clinical_review_updated_at" ON "clinical_review" ("updated_at");
DROP TRIGGER IF EXISTS "trg_clinical_review_touch" ON "clinical_review";
CREATE TRIGGER "trg_clinical_review_touch" BEFORE UPDATE ON "clinical_review" FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

-- ── System ─────────────────────────────
CREATE TABLE IF NOT EXISTS "system" (
  "rec_id" text PRIMARY KEY DEFAULT gen_rec_id(),
  "live" text,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "idx_system_updated_at" ON "system" ("updated_at");
DROP TRIGGER IF EXISTS "trg_system_touch" ON "system";
CREATE TRIGGER "trg_system_touch" BEFORE UPDATE ON "system" FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

-- ── Teams ─────────────────────────────
CREATE TABLE IF NOT EXISTS "teams" (
  "rec_id" text PRIMARY KEY DEFAULT gen_rec_id(),
  "id" text,
  "name" text,
  "primary_email" text,
  "cc_support" boolean,
  "active" boolean,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "idx_teams_id" ON "teams" ("id");
CREATE INDEX IF NOT EXISTS "idx_teams_updated_at" ON "teams" ("updated_at");
DROP TRIGGER IF EXISTS "trg_teams_touch" ON "teams";
CREATE TRIGGER "trg_teams_touch" BEFORE UPDATE ON "teams" FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

-- ── Categories ─────────────────────────────
CREATE TABLE IF NOT EXISTS "categories" (
  "rec_id" text PRIMARY KEY DEFAULT gen_rec_id(),
  "id" text,
  "name" text,
  "sort_order" bigint,
  "active" boolean,
  "team_id" text,
  "field_topic" boolean,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "idx_categories_id" ON "categories" ("id");
CREATE INDEX IF NOT EXISTS "idx_categories_team_id" ON "categories" ("team_id");
CREATE INDEX IF NOT EXISTS "idx_categories_updated_at" ON "categories" ("updated_at");
DROP TRIGGER IF EXISTS "trg_categories_touch" ON "categories";
CREATE TRIGGER "trg_categories_touch" BEFORE UPDATE ON "categories" FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

-- ── Tickets ─────────────────────────────
CREATE TABLE IF NOT EXISTS "tickets" (
  "rec_id" text PRIMARY KEY DEFAULT gen_rec_id(),
  "id" text,
  "ticket_number" bigint,
  "requester_id" text,
  "details" text,
  "contact_number" text,
  "status" text,
  "created_at" timestamptz DEFAULT now(),
  "resolved_at" timestamptz,
  "last_activity_at" timestamptz,
  "category_id" text,
  "resolution_note" text,
  "resolved_by_id" text,
  "internal_override" boolean,
  "routed_to_idtech_at" timestamptz,
  "source" text,
  "wifi_connected" boolean,
  "facility_id" text,
  "clinician_id" text,
  "updated_at" timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "idx_tickets_id" ON "tickets" ("id");
CREATE INDEX IF NOT EXISTS "idx_tickets_requester_id" ON "tickets" ("requester_id");
CREATE INDEX IF NOT EXISTS "idx_tickets_category_id" ON "tickets" ("category_id");
CREATE INDEX IF NOT EXISTS "idx_tickets_resolved_by_id" ON "tickets" ("resolved_by_id");
CREATE INDEX IF NOT EXISTS "idx_tickets_facility_id" ON "tickets" ("facility_id");
CREATE INDEX IF NOT EXISTS "idx_tickets_clinician_id" ON "tickets" ("clinician_id");
CREATE INDEX IF NOT EXISTS "idx_tickets_updated_at" ON "tickets" ("updated_at");
DROP TRIGGER IF EXISTS "trg_tickets_touch" ON "tickets";
CREATE TRIGGER "trg_tickets_touch" BEFORE UPDATE ON "tickets" FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

-- ── TicketParticipants ─────────────────────────────
CREATE TABLE IF NOT EXISTS "ticket_participants" (
  "rec_id" text PRIMARY KEY DEFAULT gen_rec_id(),
  "id" text,
  "user_id" text,
  "relationship" text,
  "added_by_id" text,
  "added_at" timestamptz,
  "ticket_id" text,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "idx_ticket_participants_id" ON "ticket_participants" ("id");
CREATE INDEX IF NOT EXISTS "idx_ticket_participants_user_id" ON "ticket_participants" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_ticket_participants_added_by_id" ON "ticket_participants" ("added_by_id");
CREATE INDEX IF NOT EXISTS "idx_ticket_participants_ticket_id" ON "ticket_participants" ("ticket_id");
CREATE INDEX IF NOT EXISTS "idx_ticket_participants_updated_at" ON "ticket_participants" ("updated_at");
DROP TRIGGER IF EXISTS "trg_ticket_participants_touch" ON "ticket_participants";
CREATE TRIGGER "trg_ticket_participants_touch" BEFORE UPDATE ON "ticket_participants" FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

-- ── TicketAssignments ─────────────────────────────
CREATE TABLE IF NOT EXISTS "ticket_assignments" (
  "rec_id" text PRIMARY KEY DEFAULT gen_rec_id(),
  "id" text,
  "user_id" text,
  "assigned_at" timestamptz,
  "ticket_id" text,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "idx_ticket_assignments_id" ON "ticket_assignments" ("id");
CREATE INDEX IF NOT EXISTS "idx_ticket_assignments_user_id" ON "ticket_assignments" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_ticket_assignments_ticket_id" ON "ticket_assignments" ("ticket_id");
CREATE INDEX IF NOT EXISTS "idx_ticket_assignments_updated_at" ON "ticket_assignments" ("updated_at");
DROP TRIGGER IF EXISTS "trg_ticket_assignments_touch" ON "ticket_assignments";
CREATE TRIGGER "trg_ticket_assignments_touch" BEFORE UPDATE ON "ticket_assignments" FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

-- ── Posts ─────────────────────────────
CREATE TABLE IF NOT EXISTS "posts" (
  "rec_id" text PRIMARY KEY DEFAULT gen_rec_id(),
  "id" text,
  "author_id" text,
  "body" text,
  "created_at" timestamptz DEFAULT now(),
  "ticket_id" text,
  "updated_at" timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "idx_posts_id" ON "posts" ("id");
CREATE INDEX IF NOT EXISTS "idx_posts_author_id" ON "posts" ("author_id");
CREATE INDEX IF NOT EXISTS "idx_posts_ticket_id" ON "posts" ("ticket_id");
CREATE INDEX IF NOT EXISTS "idx_posts_updated_at" ON "posts" ("updated_at");
DROP TRIGGER IF EXISTS "trg_posts_touch" ON "posts";
CREATE TRIGGER "trg_posts_touch" BEFORE UPDATE ON "posts" FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

-- ── Attachments ─────────────────────────────
CREATE TABLE IF NOT EXISTS "attachments" (
  "rec_id" text PRIMARY KEY DEFAULT gen_rec_id(),
  "id" text,
  "r2_object_key" text,
  "file_name" text,
  "content_type" text,
  "size_bytes" bigint,
  "uploaded_by_id" text,
  "uploaded_at" timestamptz,
  "ticket_id" text,
  "post_id" text,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "idx_attachments_id" ON "attachments" ("id");
CREATE INDEX IF NOT EXISTS "idx_attachments_uploaded_by_id" ON "attachments" ("uploaded_by_id");
CREATE INDEX IF NOT EXISTS "idx_attachments_ticket_id" ON "attachments" ("ticket_id");
CREATE INDEX IF NOT EXISTS "idx_attachments_post_id" ON "attachments" ("post_id");
CREATE INDEX IF NOT EXISTS "idx_attachments_updated_at" ON "attachments" ("updated_at");
DROP TRIGGER IF EXISTS "trg_attachments_touch" ON "attachments";
CREATE TRIGGER "trg_attachments_touch" BEFORE UPDATE ON "attachments" FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

-- ── EmailLog ─────────────────────────────
CREATE TABLE IF NOT EXISTS "email_log" (
  "rec_id" text PRIMARY KEY DEFAULT gen_rec_id(),
  "id" text,
  "to_addrs" text,
  "cc_addrs" text,
  "subject" text,
  "status" text,
  "provider_message_id" text,
  "created_at" timestamptz DEFAULT now(),
  "ticket_id" text,
  "post_id" text,
  "updated_at" timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "idx_email_log_id" ON "email_log" ("id");
CREATE INDEX IF NOT EXISTS "idx_email_log_provider_message_id" ON "email_log" ("provider_message_id");
CREATE INDEX IF NOT EXISTS "idx_email_log_ticket_id" ON "email_log" ("ticket_id");
CREATE INDEX IF NOT EXISTS "idx_email_log_post_id" ON "email_log" ("post_id");
CREATE INDEX IF NOT EXISTS "idx_email_log_updated_at" ON "email_log" ("updated_at");
DROP TRIGGER IF EXISTS "trg_email_log_touch" ON "email_log";
CREATE TRIGGER "trg_email_log_touch" BEFORE UPDATE ON "email_log" FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

-- ── ConflictCategories ─────────────────────────────
CREATE TABLE IF NOT EXISTS "conflict_categories" (
  "rec_id" text PRIMARY KEY DEFAULT gen_rec_id(),
  "id" text,
  "value" text,
  "label" text,
  "sort_order" bigint,
  "is_active" boolean,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "idx_conflict_categories_id" ON "conflict_categories" ("id");
CREATE INDEX IF NOT EXISTS "idx_conflict_categories_updated_at" ON "conflict_categories" ("updated_at");
DROP TRIGGER IF EXISTS "trg_conflict_categories_touch" ON "conflict_categories";
CREATE TRIGGER "trg_conflict_categories_touch" BEFORE UPDATE ON "conflict_categories" FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

-- ── Clinicians ─────────────────────────────
CREATE TABLE IF NOT EXISTS "clinicians" (
  "rec_id" text PRIMARY KEY DEFAULT gen_rec_id(),
  "id" text,
  "esper_id" text,
  "first_name" text,
  "last_name" text,
  "name" text,
  "discipline" text,
  "worker_id" text,
  "device_serial" text,
  "device_name" text,
  "email" text,
  "last_seen_at" timestamptz,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "idx_clinicians_id" ON "clinicians" ("id");
CREATE INDEX IF NOT EXISTS "idx_clinicians_esper_id" ON "clinicians" ("esper_id");
CREATE INDEX IF NOT EXISTS "idx_clinicians_worker_id" ON "clinicians" ("worker_id");
CREATE INDEX IF NOT EXISTS "idx_clinicians_updated_at" ON "clinicians" ("updated_at");
DROP TRIGGER IF EXISTS "trg_clinicians_touch" ON "clinicians";
CREATE TRIGGER "trg_clinicians_touch" BEFORE UPDATE ON "clinicians" FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

-- ── api_access_log (server-side access accounting; not an Airtable table) ──
CREATE TABLE IF NOT EXISTS "api_access_log" (
  "rec_id" text PRIMARY KEY DEFAULT gen_rec_id(),
  "actor_sub" text,
  "actor_user_id" text,
  "method" text NOT NULL,
  "table_name" text NOT NULL,
  "row_rec_id" text,
  "row_count" integer,
  "query_summary" text,
  "status" integer,
  "at" timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "idx_api_access_log_at" ON "api_access_log" ("at");
CREATE INDEX IF NOT EXISTS "idx_api_access_log_actor" ON "api_access_log" ("actor_sub");
