/**
 * formula.js — Airtable `filterByFormula` → parameterized PostgreSQL WHERE.
 *
 * The grammar is CLOSED: every formula in both frontends is generated by our
 * own code (~18 structural patterns — see the migration plan research).
 * Anything outside the grammar throws FormulaError → the API responds 400
 * loudly instead of guessing.
 *
 * Supported:
 *   {field} = "v" | 'v' | number      equality (checkbox: {f} = 1 / {f} = 0)
 *   {field} != "v"                    inequality
 *   {field} > n, >= n, < n, <= n      numeric comparison
 *   {field} = ""                      empty check
 *   FIND("v", ARRAYJOIN({field}))     link/containment → equality on stored id
 *   FIND("v", {field})                substring → ILIKE
 *   SEARCH("v", {field}) > 0          substring → ILIKE
 *   NOT(expr)
 *   IS_AFTER({field}, "iso") / IS_BEFORE({field}, "iso")
 *   AND(e1, e2, …) / OR(e1, e2, …)
 *
 * Output: { sql, params } where params are positional ($1…$n string values)
 * — field names are validated against the table registry (whitelist), never
 * interpolated from user input.
 */

export class FormulaError extends Error {}

// ── Tokenizer ─────────────────────────────────────────────────────────────────
function tokenize(input) {
  const tokens = [];
  let i = 0;
  const s = input;
  while (i < s.length) {
    const c = s[i];
    if (/\s/.test(c)) { i++; continue; }
    if (c === '{') {
      const end = s.indexOf('}', i);
      if (end === -1) throw new FormulaError('Unterminated field reference');
      tokens.push({ t: 'field', v: s.slice(i + 1, end) });
      i = end + 1;
      continue;
    }
    if (c === '"' || c === "'") {
      let j = i + 1;
      let out = '';
      while (j < s.length && s[j] !== c) {
        if (s[j] === '\\' && s[j + 1] === c) { out += c; j += 2; continue; }
        out += s[j];
        j++;
      }
      if (j >= s.length) throw new FormulaError('Unterminated string literal');
      tokens.push({ t: 'str', v: out });
      i = j + 1;
      continue;
    }
    if (/[0-9]/.test(c) || (c === '-' && /[0-9]/.test(s[i + 1] || ''))) {
      let j = i + 1;
      while (j < s.length && /[0-9.]/.test(s[j])) j++;
      tokens.push({ t: 'num', v: s.slice(i, j) });
      i = j;
      continue;
    }
    if (/[A-Za-z_]/.test(c)) {
      let j = i;
      while (j < s.length && /[A-Za-z_0-9]/.test(s[j])) j++;
      tokens.push({ t: 'name', v: s.slice(i, j).toUpperCase() });
      i = j;
      continue;
    }
    if (c === '(' || c === ')' || c === ',') { tokens.push({ t: c }); i++; continue; }
    if (c === '!' && s[i + 1] === '=') { tokens.push({ t: 'op', v: '!=' }); i += 2; continue; }
    if (c === '>' && s[i + 1] === '=') { tokens.push({ t: 'op', v: '>=' }); i += 2; continue; }
    if (c === '<' && s[i + 1] === '=') { tokens.push({ t: 'op', v: '<=' }); i += 2; continue; }
    if (c === '=' || c === '>' || c === '<') { tokens.push({ t: 'op', v: c }); i++; continue; }
    throw new FormulaError(`Unexpected character "${c}" at ${i}`);
  }
  return tokens;
}

// ── Parser (recursive descent → AST) ─────────────────────────────────────────
function parse(tokens) {
  let pos = 0;
  const peek = () => tokens[pos];
  const next = () => tokens[pos++];
  const expect = (t) => {
    const tok = next();
    if (!tok || tok.t !== t) throw new FormulaError(`Expected "${t}"`);
    return tok;
  };

  function parseExpr() {
    const tok = peek();
    if (!tok) throw new FormulaError('Unexpected end of formula');

    if (tok.t === 'name') {
      next();
      const fn = tok.v;
      expect('(');
      const args = [];
      if (peek() && peek().t !== ')') {
        args.push(parseExpr());
        while (peek() && peek().t === ',') { next(); args.push(parseExpr()); }
      }
      expect(')');
      const node = { type: 'call', fn, args };
      return maybeComparison(node);
    }

    if (tok.t === 'field') {
      next();
      return maybeComparison({ type: 'field', name: tok.v });
    }
    if (tok.t === 'str') { next(); return { type: 'str', value: tok.v }; }
    if (tok.t === 'num') { next(); return { type: 'num', value: tok.v }; }
    if (tok.t === '(') { next(); const e = parseExpr(); expect(')'); return maybeComparison(e); }
    throw new FormulaError(`Unexpected token "${tok.t}"`);
  }

  function maybeComparison(left) {
    const tok = peek();
    if (tok && tok.t === 'op') {
      next();
      const right = parseExpr();
      return { type: 'cmp', op: tok.v, left, right };
    }
    return left;
  }

  const ast = parseExpr();
  if (pos !== tokens.length) throw new FormulaError('Trailing tokens in formula');
  return ast;
}

// ── Compiler (AST → SQL) ──────────────────────────────────────────────────────
export function compileFormula(formula, tableDef) {
  const params = [];
  const P = (v) => { params.push(v); return `$${params.length}`; };

  function col(fieldName) {
    const def = tableDef.fields[fieldName];
    if (!def) throw new FormulaError(`Unknown field {${fieldName}}`);
    return { ref: `"${def.column}"`, def };
  }

  // Unwrap LOWER({field}) → the field node + a case-fold flag.
  function fieldOperand(node) {
    if (node?.type === 'call' && node.fn === 'LOWER' && node.args.length === 1 && node.args[0].type === 'field') {
      return { fieldNode: node.args[0], lower: true };
    }
    if (node?.type === 'field') return { fieldNode: node, lower: false };
    return null;
  }

  function compare(node) {
    const { op, left, right } = node;
    // SEARCH(...) > 0 → the SEARCH itself is the predicate.
    if (left.type === 'call' && left.fn === 'SEARCH' && op === '>' && right.type === 'num') {
      return compileNode(left);
    }
    // RECORD_ID() = 'recXXX' → primary-key match (Support app user/clinician
    // resolution pattern).
    if (left.type === 'call' && left.fn === 'RECORD_ID' && left.args.length === 0) {
      if (right.type !== 'str') throw new FormulaError('RECORD_ID() compares against a string');
      if (op === '=') return `"rec_id" = ${P(right.value)}`;
      if (op === '!=') return `"rec_id" <> ${P(right.value)}`;
      throw new FormulaError(`Unsupported RECORD_ID() operator ${op}`);
    }
    const operand = fieldOperand(left);
    if (!operand) throw new FormulaError('Comparison must start with a field');
    let { ref, def } = col(operand.fieldNode.name);
    if (operand.lower) ref = `LOWER(${ref}::text)`;

    if (right.type === 'str') {
      const v = right.value;
      if (v === '') {
        if (op === '=') return `(${ref} IS NULL OR ${ref}::text = '')`;
        if (op === '!=') return `(${ref} IS NOT NULL AND ${ref}::text <> '')`;
      }
      // Text compare mirrors Airtable string equality; range ops on temporal
      // columns cast the operand.
      if (op === '=') return `${ref}::text = ${P(v)}`;
      if (op === '!=') return `(${ref} IS NULL OR ${ref}::text <> ${P(v)})`;
      if (['>', '<', '>=', '<='].includes(op)) {
        const cast = def.wire === 'timestamp' || def.wire === 'date' ? '::timestamptz' : '';
        return `${ref} ${op} ${P(v)}${cast}`;
      }
    }
    if (right.type === 'num') {
      const n = right.value;
      if (def.wire === 'checkbox') {
        if (op === '=' && n === '1') return `${ref} IS TRUE`;
        if (op === '=' && n === '0') return `${ref} IS NOT TRUE`;
      }
      if (op === '=') return `${ref} = ${P(n)}::numeric`;
      if (op === '!=') return `(${ref} IS NULL OR ${ref} <> ${P(n)}::numeric)`;
      return `${ref} ${op} ${P(n)}::numeric`;
    }
    throw new FormulaError(`Unsupported comparison operand (${right.type})`);
  }

  function compileNode(node) {
    switch (node.type) {
      case 'cmp':
        return compare(node);
      case 'call': {
        const { fn, args } = node;
        if (fn === 'AND' || fn === 'OR') {
          if (args.length === 0) throw new FormulaError(`${fn}() needs arguments`);
          return `(${args.map(compileNode).join(` ${fn} `)})`;
        }
        if (fn === 'NOT') {
          if (args.length !== 1) throw new FormulaError('NOT() takes one argument');
          return `NOT (${compileNode(args[0])})`;
        }
        if (fn === 'FIND' || fn === 'SEARCH') {
          // FIND/SEARCH("v", ARRAYJOIN({col})) — link/array containment — or
          // FIND/SEARCH("v", {col}) — substring. Both apps use both spellings.
          let [needle, hay] = args;
          // LOWER('literal') needle → fold the literal (Support user search).
          if (needle?.type === 'call' && needle.fn === 'LOWER' && needle.args[0]?.type === 'str') {
            needle = { type: 'str', value: needle.args[0].value.toLowerCase() };
          }
          if (!needle || needle.type !== 'str') throw new FormulaError(`${fn}() first arg must be a string`);

          let fieldNode = hay;
          let viaArrayJoin = false;
          if (hay?.type === 'call' && hay.fn === 'ARRAYJOIN') {
            fieldNode = hay.args[0];
            viaArrayJoin = true;
          } else {
            const operand = fieldOperand(hay); // unwraps LOWER({field})
            if (operand) fieldNode = operand.fieldNode;
          }
          if (!fieldNode || fieldNode.type !== 'field') throw new FormulaError(`${fn}() second arg must reference a field`);
          const { ref, def } = col(fieldNode.name);

          if (viaArrayJoin && def.wire === 'linkArray' && def.linkTable) {
            // Callers pass either the target's rec id or its business id.
            // Stored value is the rec_id — match either directly or via the
            // target table's business id.
            const targetPg = tableDef.registry[def.linkTable]?.pgTable;
            const p = P(needle.value);
            if (targetPg) {
              return `(${ref} = ${p} OR ${ref} IN (SELECT rec_id FROM "${targetPg}" WHERE id = ${p}))`;
            }
            return `${ref} = ${p}`;
          }
          if (def.wire === 'textArray') {
            return `${P(needle.value)} = ANY(${ref})`;
          }
          // Plain text containment. ILIKE keeps SEARCH's case-insensitive
          // semantics (harmless for FIND's id-containment call sites).
          return `${ref}::text ILIKE '%' || ${P(needle.value)} || '%'`;
        }
        if (fn === 'IS_AFTER' || fn === 'IS_BEFORE') {
          const [fieldNode, when] = args;
          if (fieldNode?.type !== 'field' || when?.type !== 'str') throw new FormulaError(`${fn}({field}, "iso") expected`);
          const { ref } = col(fieldNode.name);
          return `${ref} ${fn === 'IS_AFTER' ? '>' : '<'} ${P(when.value)}::timestamptz`;
        }
        throw new FormulaError(`Unsupported function ${fn}()`);
      }
      case 'field': {
        // Bare {checkbox_field} used as predicate.
        const { ref, def } = col(node.name);
        if (def.wire === 'checkbox') return `${ref} IS TRUE`;
        return `(${ref} IS NOT NULL AND ${ref}::text <> '')`;
      }
      default:
        throw new FormulaError(`Cannot compile node type "${node.type}"`);
    }
  }

  const sql = compileNode(parse(tokenize(formula)));
  return { sql, params };
}
